version: "3.3"

services:
  proxy:
    image: nginx:1.15-alpine
    container_name: proxy
    ports:
      - 5000:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - capju
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    restart: always
    ports:
      - 5432:5432
    networks:
      - capju
    env_file:
      - .env

networks:
  capju:
    name: capju
